services:
  postgres-batch:
    image: postgres:latest
    container_name: postgres-batch
    hostname: postgres-batch
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c", "max_connections=200"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-batch-data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
    driver: bridge

volumes:
  postgres-batch-data:
